### ISSUE TITLE
update and Sync-IcingaRepository failed

### ISSUE THREAD

**Issue by puseidr** [Icinga/icinga-powershell-framework#399]
its not possible to update the icingarepository or even create a new one

when i use `Update-IcingaRepository` or `Sync-IcingaRepository` i always get the message:
```
[Error]: The repository hash for the cloned repository is not matching the file hash of the files inside. Removing repository data
```

i've already updated to framework 1.7.0 but its also not working with 1.6.1

**Comment by LordHepipud** [comment]
Thank you for the issue. Could you please test the linked PR and check if this resolves the problem?
This should resolve the problem, once v1.7.1 is installed. For updating, you will require to use the `-ForceTrust` at the moment to update, because the hash can never be valid, caused by fix for generating the repository hash in general: #381

**Comment by puseidr** [comment]
Sync-IcingaRepository still fails (without -ForceTrust parameter) with this pullrequest, but it works with -ForceTrust

**Comment by LordHepipud** [comment]
Have you rebuild the Framework cache after modifying the files with `icinga -RebuildCache`?

**Comment by puseidr** [comment]
no, but i've retried it with `icinga -RebuildCache` and now it works. Thanks!

**Comment by LordHepipud** [comment]
You are welcome. I will tag v1.7.1 today.

Thank you for testing!
