### ISSUE TITLE
Error on creating certificates if hostname is set to custom

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icinga-powershell-framework#505]
1) change the hostname to a custom one by setting
"IfW-Hostname":{"Selection":"6"}, "IfW-CustomHostname":{"Values":["testtest"]}
2) run the installer 
3) get registered at director with my hostname LaptopXYXY 
4) [Notice]: Starting Icinga for Windows installation
5) I get the message ([Notice]: Your hostname was successfully changed to "TESTTEST") 
6) Certificate Creation gives me troubles. [Error]: Failed to create certificate

## Expected Behavior
Registration should be done with the override hostname

## Current Behavior
Registration is not done with the override hostname

## Possible Solution
I have added a solution for the old installer if that helps
https://github.com/Icinga/icinga-powershell-framework/pull/502

## Steps to Reproduce (for bugs)
use iwf-config with override hostname

## Your Environment

Major  Minor  Build  Revision
5     /   1      /   22000 /  282 

icinga director 1.9
icinga powershell framework 1.8
Windows 11

**Comment by moreamazingnick** [comment]
#506

**Comment by LordHepipud** [comment]
Thank you for the issue and the PR. Could you please test this with the current v1.9.1 release?
Based on my testing so far, this error should be resolved by now.

**Comment by moreamazingnick** [comment]
Problem still there with 1.9.1.
It's very strange because the hostname is NOT overwritten when generating a ticket or registering at director, but for generating the certificate it is the new hostname.
looks like the data is not available shortly after the change
Best regards Nicolas

**Comment by LordHepipud** [comment]
Do you modify the hostname before or after registering the host inside the Icinga Director?
You have to modify it before doing the registration process.

This is a very odd issue, because it just works fine for me.

**Comment by moreamazingnick** [comment]
It happens when I register a new host with a custom hostname. I think it is some kind of a race condition, because with my voodoo PR the registration works :)
